### ISSUE TITLE
关于Firework_Simulator的致歉

### ISSUE THREAD

**Issue by laulzgoay** [NianBroken/Firework_Simulator#2]
在上线之初较为仓促的情况下在获取到源代码后参考并复制了互联网上现有的翻译，整合为了我的版本，我网站上线后，我将文件直接上传Github并未标注原二次开发人员，是我的失误，违背了开源精神，鉴于我Firework_Simulator库并未有人Wacth&Star，未对原项目构成损失，我已将涉事源码删除，并于我网站页脚增加标注原二次开发人员，在此，再次表达我的歉意！新春之际，祝您新春快乐！

**Comment by NianBroken** [comment]
新春快乐！
