### ISSUE TITLE
是否可以添加一些文字烟花效果?

### ISSUE THREAD

**Issue by HaoDong108** [NianBroken/Firework_Simulator#6]
是否可以考虑添加一些文字烟花效果? 例如给一个数组从中随机一段文字或者顺序全部文本直到完毕

**Comment by LovelyLM** [comment]
我觉得不错 适合表白

**Comment by HaoDong108** [comment]
除此之外，希望还能有图像烟花，例如用二值化，然后取出轮廓中的一些点阵。我自己克隆尝试做了一个版本 [http://haodong108.gitee.io/fireworks-2023/](http://haodong108.gitee.io/fireworks-2023/)，但是由于算法不太行，绽放效果不怎么理想😂

**Comment by LovelyLM** [comment]
> 

还不错啊 有雏形的效果了

**Comment by dainil** [comment]
能不能开源图像烟花，学习学习以下

**Comment by NianBroken** [comment]
> 除此之外，希望还能有图像烟花，例如用二值化，然后取出轮廓中的一些点阵。我自己克隆尝试做了一个版本 http://haodong108.gitee.io/fireworks-2023/，但是由于算法不太行，绽放效果不怎么理想😂

非常感谢！

**Comment by 861** [comment]
文字烟花用手机浏览器查看无法显示
