### ISSUE TITLE
烟花爆炸的后的残影如何快速清空掉？

### ISSUE THREAD

**Issue by realwugang** [NianBroken/Firework_Simulator#9]
请问烟花爆炸后如何清除透明背景下的残影
<img width="508" alt="image" src="https://github.com/NianBroken/Firework_Simulator/assets/26088619/6decb2ee-866a-4a1a-9fd2-3b1bf550a117">

**Comment by NianBroken** [comment]
> 请问烟花爆炸后如何清除透明背景下的残影 <img alt="image" width="508" src="https://private-user-images.githubusercontent.com/26088619/301749717-6decb2ee-866a-4a1a-9fd2-3b1bf550a117.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MzE4MzQsIm5iZiI6MTcwNjkzMTUzNCwicGF0aCI6Ii8yNjA4ODYxOS8zMDE3NDk3MTctNmRlY2IyZWUtODY2YS00YTFhLTlmZDItM2IxYmY1NTBhMTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAzMzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NjFjNzQ4MTRlNTM2ODE1NDU0NGMyYjBlODU2ZDQ5ODVlZWI2YzMzNmRmMTkyM2EzNTQ2ZWZlMzE5Mzk1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DXgHff5yMdogU6nXfCU9x0SdUSA-eazVEc0H_SxovKA">

关掉`保留烟花的火花`即可

![image](https://github.com/NianBroken/Firework_Simulator/assets/57057288/95185d1f-d46f-4eec-9536-7ed8422fd0c6)
